name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies for Client
      run: |
        cd client
        npm install

    - name: Build Client
      run: |
        cd client
        npm run build

    - name: Install dependencies for Admin
      run: |
        cd admin
        npm install

    - name: Build Admin
      run: |
        cd admin
        npm run build
        
